//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OmafLogin.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class User
    {
        public int UserId { get; set; }
        [DisplayName("User Name")]
        [Required(ErrorMessage ="Please enter username.")]
        public string UserName { get; set; }
        [DataType(DataType.Password)]
        [Required(ErrorMessage = "Please enter password.")]
        public string Password { get; set; }
        public string CDI { get; set; }
        public string QA { get; set; }
        public string MC { get; set; }
        public string SFF { get; set; }
        public string LoginErrorMsg { get; set; }
    }
}
